name: blockbuster_env
channels:
  - conda-forge
  - defaults
dependencies:
  # Python and necessary packages
  - python=3.8
  - numpy
  - matplotlib
  - statsmodels  # Added statsmodels package
  - seaborn
  - demes
  - demesdraw

  # C Compiler and dependencies
  - gcc
  - make
  - gmp
  - openmp

  # Additional utilities
  - cmake
  - pkg-config

  # Optional: System utilities for file handling
  - coreutils
  - findutils
  - libgcc

