name: blockbuster_env
channels:
  - conda-forge
  - defaults
dependencies:
  # Python and necessary packages
  - python=3.8
  - numpy
  - matplotlib
  - statsmodels  # Added statsmodels package
  - seaborn

  # C Compiler and dependencies
  # C Compiler and dependencies
  - gcc
  - make
  - gmp             # GMP: required by MPFR
  - lapacke         # LAPACKE: C interface to LAPACK
  - openblas        # OpenBLAS: BLAS implementation (used by LAPACK)
  - libblas         # For completeness (used with LAPACK)
  - liblapack       # For completeness (used with LAPACK)
  - libgfortran     # Needed by BLAS/LAPACK

  # Additional utilities
  - cmake
  - pkg-config

  # Optional: System utilities for file handling
  - coreutils
  - findutils
  - libgcc

